tosca_definitions_version: tosca_simple_yaml_1_3

imports:

- namespace_prefix: o11n
  file: ../../orchestration/1.0/profile.yaml

node_types:

  Release:
    description: >-
      Helm release
    properties:
      name:
        description: >-
          Release name. If not specified will use node template name.
        type: string
        required: false
      chart:
        description: >-
          URL to the chart (as with "helm install"). Can point to an archive (tarball) or path to
          a local directory. This can be a "get_artifact" function call (see the Chart artifact
          type).
        type: string
      values:
        description: >-
          Set chart values (as with "helm install --set"). If both "values" and "valuesUrl" are
          used and overlap, "values" will override "valuesUrl".
        type: map
        entry_schema: string
        required: false
      valuesUrl:
        description: >-
          URL to a YAML file with chart values (as with "helm install --values").
        type: string
        required: false
    interfaces:
      orchestration:
        type: o11n:ScriptletOrchestration
        operations:
          provision: helm.install
