apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding

metadata:
  name: turandot

subjects:
- kind: ServiceAccount
  name: turandot
  namespace: !!string $NAMESPACE # required

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
