tosca_definitions_version: tosca_simple_yaml_1_3

imports:

- namespace_prefix: helm
  file: profiles/helm/1.0/profile.yaml

topology_template:

  node_templates:

    hello-world:
      type: helm:Release
      properties:
        chart: { get_artifact: [ SELF, chart ] }
        values:
          nameOverride: helm # will be used as a postfix
          service.type: LoadBalancer
          service.port: '8080'
      artifacts:
        chart:
          type: helm:Chart
          file: artifacts/charts/hello-world.tar.gz
